augmentation:
  scale_range: 0.4
  theta_range: 40.0
batch_size: 16
epochs: 100
heatmap_sigma: 2.0
learning_rates:
  start: 1.0e-3
  decay: 0.1
  steps: [40, 80]
optimizer:
  type: "Adam"
val_fraction: 0.0
