augmentation:
  scale_range: 0.2
  theta_range: 20.0
batch_size: 16
epochs: 100
heatmap_sigma: 2.0
initial_weights_path:
  - "weights"
  - "hrnet_jhmdb_mpii_init.pth"
learning_rates:
  start: 5.0e-6
  decay: 0.1
  steps: []
optimizer:
  type: "AdamW"
  weight_decay: 100.0
val_fraction: 0.2
